server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: utf-8
spring:
  mvc:
    view:
      suffix: .html
      prefix: classpath:/templates/
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.132.67.200:3306/personal_website?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&tinyInt1isBit=true&useAffectedRows=true&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: root
    password: root123
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
    # Lettuce连接池的相关配置
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
springfox:
  documentation:
    swagger:
      v2.path: /api-docs
swagger:
  base-package: com.fc.controller

mybatis-plus:
  type-aliases-package: com.fc.entity
#  type-enums-package: com.csvw.sx.gateway.common.**.entity.enums
  mapper-locations: "classpath*:/mappers/**/*.xml"
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)